# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('t', 'testing'), ('p', 'production')], max_length=1)),
                ('date', models.DateField(verbose_name='date of deployment')),
                ('run', models.CharField(choices=[('y', 'yes'), ('n', 'not')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField(verbose_name='completions date')),
                ('state', models.CharField(default='success', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kb_name', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, verbose_name='date of release')),
                ('classification', models.CharField(choices=[('s', 'security'), ('c', 'critical'), ('o', 'other'), ('n', 'not defined')], default='n', max_length=1)),
                ('product', models.CharField(choices=[('w7', 'windows 7'), ('w10', 'windows 10'), ('o10', 'office 10'), ('o13', 'office 13'), ('oth', 'other product')], max_length=4)),
                ('belongs_rule', models.ManyToManyField(blank=True, to='updcalendar.Rule', verbose_name='belongs to rule')),
            ],
        ),
    ]
